### ISSUE TITLE
Get git hooks running

### ISSUE THREAD

**Issue by ejfrancis** [intuit/judo#20]
At one point in time we had used the `husky` package to run `prepush` and `precommit` scripts in `package.json` as git hooks to enforce code linting and coverage. It looks like it's not working anymore, I'll have to investigate. 

I believe we had used an internal package at Intuit when this was not a public repo and perhaps we forgot to replace it with the standard `husky` package when moving to open source.

**Comment by paulolorenzobasilio** [comment]
Hi, I would love to work on this.

**Comment by ktamilvanan** [comment]
Dibs. I will add this config.
