### ISSUE TITLE
CircleCI is not running on PR/merge

### ISSUE THREAD

**Issue by worldjoe** [intuit/judo#29]
**Is this a bug report, or a feature request?**
Bug.
**What is the current behavior?**
On PRs, CircleCI doesn't run. Oddly it runs for dependabot changes, but not other people's - like https://github.com/intuit/judo/pull/28
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo repo of the problem.**
create a PR with a syntax error, note that Circle CI does not complain.

**What is the expected behavior?**
CircleCI should catch compilation errors, linting, etc issues.

**Comment by KamiKillertO** [comment]
Did you check you circle ci config ? There's one that make circle run builds/workflows for forks
<img width="1525" alt="Capture d’écran 2019-09-26 à 17 07 51" src="https://user-images.githubusercontent.com/9579729/65700606-3a4be980-e080-11e9-803d-4163283bb9d8.png">

**Comment by ejfrancis** [comment]
@worldjoe it looks I don't have access to the CircleCI job config anymore, can you check this when you've got a chance?

**Comment by worldjoe** [comment]
Turns out circleci needed to be re-authed to my account.
