### ISSUE TITLE
Update code to pass all our security alerts

### ISSUE THREAD

**Issue by worldjoe** [intuit/judo#30]
**Is this a bug report, or a feature request?**
Feature
**What is the current behavior?**
We have a few security issues that dependabot can't fix itself. Update our code for all of them:
https://github.com/intuit/judo/network/alerts

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo repo of the problem.**
https://github.com/intuit/judo/network/alerts

**What is the expected behavior?**
No alerts listed here when done:
https://github.com/intuit/judo/network/alerts

**Comment by vvscode** [comment]
`https://github.com/intuit/judo/network/alerts` page not found

**Comment by vvscode** [comment]
@worldjoe  maybe because of the fact, that it's private page

can you share the report here?

**Comment by mcrosby114** [comment]
Hmm, yeah cannot access the security report either. Going to need that or further info to proceed on the issue.

**Comment by worldjoe** [comment]
![Screen Shot 2019-10-03 at 10 22 13 AM](https://user-images.githubusercontent.com/876352/66149367-cea9d500-e5c7-11e9-9b08-f7c41415a8b9.png)

**Comment by worldjoe** [comment]
Passing! Thanks.
