### ISSUE TITLE
Security updates

### ISSUE THREAD

**Issue by worldjoe** [intuit/judo#44]
Update for security issues. Please test before creating your PR.

`Remediation

Upgrade node-fetch to version 2.6.1 or later. For example:

"dependencies": {
  "node-fetch": ">=2.6.1"
}

or…

"devDependencies": {
  "node-fetch": ">=2.6.1"
}

`

`Remediation

Upgrade acorn to version 5.7.4 or later. For example:

"dependencies": {
  "acorn": ">=5.7.4"
}

or…

"devDependencies": {
  "acorn": ">=5.7.4"
}

`

`Remediation

Upgrade minimist to version 0.2.1 or later. For example:

"dependencies": {
  "minimist": ">=0.2.1"
}

or…

"devDependencies": {
  "minimist": ">=0.2.1"
}

`

`Remediation

Upgrade kind-of to version 6.0.3 or later. For example:

"dependencies": {
  "kind-of": ">=6.0.3"
}

or…

"devDependencies": {
  "kind-of": ">=6.0.3"
}

`

**Comment by worldjoe** [comment]
<img width="1002" alt="Screen Shot 2020-10-06 at 8 29 15 AM" src="https://user-images.githubusercontent.com/876352/95223093-0b497700-07ae-11eb-82d4-e77da652a87c.png">

**Comment by kishore-tw** [comment]
can you assign me on this?

**Comment by Kishore-abhimanyu** [comment]
can you assign me on this?

**Comment by umer2001** [comment]
can I do this ?

**Comment by worldjoe** [comment]
there's no assignment or dibs. Either do it and send a PR, or don't.

**Comment by umer2001** [comment]
done,
please merge it.
